### ISSUE TITLE
トンボの仕上がり位置がdocumentclassで指定したサイズと一致しない

### ISSUE THREAD

**Issue by nutti** [aminophen/gentombow#10]
gentombowを使わせていただいている者です。
突然で大変恐縮ですが、1点教えていただきたいことがあります。

lualatexを使って、以下のようなTexのコードからPDFを作成したときに、本来であれば、トンボの仕上がり位置がdocumentclassで指定したサイズと一致すべきところ、トンボの塗り足し位置と一致してしまい、正しい結果が得られません。

```tex
\documentclass[10pt,b5paper,twoside,tombo]{ltjbook}
\usepackage[pdfbox,tombo-a4]{gentombow}
\usepackage[size=a4paper]{bxpapersize}
```

`gentombow` などのオプションを変更しても同様で、実際にPDFを印刷したときもサイズの不一致が発生します。
もし本現象につきまして、何かしら情報をお持ちでしたら教えていただけると大変助かります。
また、追加の情報が必要であれば、可能な範囲でお渡しできると思います。

#### 環境

* **OS:** Ubuntu 18.04
* **TexLive:** texlive-luatex=2017.20180305-1
* **LuaLatexコマンド:** `lualatex -halt-on-error -interaction=nonstopmode -file-line-error --shell-escape --output-directory=output_dir input.tex`

**Comment by nutti** [comment]
こちらでもう少し調べてみました。
geometryパッケージを利用して余白を変更したときに、本現象が発生するようです。

```tex
\documentclass[10pt,b5paper,twoside,tombo]{ltjbook}
\usepackage[pdfbox,tombo-a4]{gentombow}
\usepackage[size=a4paper]{bxpapersize}
\usepackage[top=17truemm,bottom=10truemm,left=13truemm,right=13truemm]{geometry}
```

gentombowの内部を確認したところ、以下の `\@@paperwidth` が正しい値を返していないようでした。
ここの値を直接入力してンボの出力位置を調節することで今回は回避できそうですが、今後geometryパッケージと共存してgentombowを利用することは検討されていますでしょうか？

```tex
\def\@outputtombow{%
  \iftombow
  \vbox to\z@{\kern-\dimexpr 10mm+\@tombowbleed\relax\relax
    \boxmaxdepth\maxdimen
    \moveleft\@tombowbleed \vbox to\@@paperheight{%
    \color@begingroup
      \@tombowcolor
      \hbox to\@@paperwidth{\hskip\@tombowbleed\relax
         \copy\@TL\hfill\copy\@TC\hfill\copy\@TR\hskip\@tombowbleed}%
      \kern-10mm
      \hbox to\@@paperwidth{\copy\@Tl\hfill\copy\@Tr}%
      \vfill
      \hbox to\@@paperwidth{\copy\@CL\hfill\copy\@CR}%
      \vfill
      \hbox to\@@paperwidth{\copy\@Bl\hfill\copy\@Br}%
      \kern-10mm
      \hbox to\@@paperwidth{\hskip\@tombowbleed\relax
         \copy\@BL\hfill\copy\@BC\hfill\copy\@BR\hskip\@tombowbleed}%
    \color@endgroup
    }\vss
  }%
  \fi
}
```

**Comment by aminophen** [comment]
まだ十分調べられていませんが，gentombow パッケージが用紙サイズを計算した**後**に geometry が用紙サイズを変更するのは想定外です。治るかどうかわかりませんが，geometry パッケージを先に読み込んで試してみてください。

（ドキュメントに書いていなくてすみません。）

**Comment by aminophen** [comment]
ちなみに：（これは gentombow パッケージとは関係ありませんが，）

\documentclass のオプションに b5paper とある場合，これはグローバル扱いのため，geometry パッケージも自分への指示であると認識します。ltjbook クラスの b5paper は JIS B5 ですが，geometry パッケージの b5paper は ISO B5 ですので，

``` tex
\documentclass[b5paper]{ltjbook}
\usepackage{geometry}
```

というソースでは後から読み込まれた geometry パッケージの方が勝って ISO B5 の用紙サイズになると思います。これが意図通りならばそれで良いですが，

* b5paper の代わりに b5j とすれば，JIS B5 になると思います。
* \usepackage[pass,...]{geometry} のように pass というオプションを追加すれば，geometry が用紙サイズを変更しなくなるようです。

ご参考まで。

**Comment by nutti** [comment]
情報ありがとうございます。

> geometry パッケージを先に読み込んで試してみてください。

こちらはすでに試しており、先にgeometryパッケージを読み込んだ場合でも同様にトンボの位置がずれる現象が発生します。

> ltjbook クラスの b5paper は JIS B5 ですが，geometry パッケージの b5paper は ISO B5 

本件、初めて知りました。ありがとうございます。
しかし、passオプションを追加したことにより、geometryパッケージで変更した余白も適用されなくなってしまいました。

**Comment by aminophen** [comment]
こちらでは「b5j オプションを使う＋geometry を先に読込」で正常に動いているように見えます。

* プリアンブルだけではなく，問題が再現する完全なソースファイル（出来れば最小化したものが better）を頂けますか？
* そのソースファイル冒頭に \listfiles というコマンドを付けると各パッケージのバージョン一覧がログに出ると思いますが，それを見せてください。

**Comment by nutti** [comment]
本文を除いた最小構成のtexファイルと、\listfilesによって出力された各パッケージ一覧を添付します。よろしくお願いします。

[files.zip](https://github.com/aminophen/gentombow/files/3901858/files.zip)

**Comment by nutti** [comment]
> 「b5j オプションを使う＋geometry を先に読込」

すみません。
こちらの環境で、b5jのオプションをtexファイルに正しく適用できていないために、問題が発生してしまっているようでした。
提示いただいた方法で正しく動作しているようです。

現状問題はなさそうなので、本Issueはクローズとさせていただきます。
いろいろとありがとうございました。とても助かりました。
