### ISSUE TITLE
デジタルトンボ

### ISSUE THREAD

**Issue by aminophen** [aminophen/gentombow#2]
abenori/jlreq#26 参照。

- トンボ付きのひとまわり大きな紙面のサイズの定義（仕上がりは紙面中央に配置される）。

までは gentombow パッケージで完了しているが，

- そのサイズに MediaBox, CropBox を設定
- PDFのために BleedBox, TrimBox, ArtBox(TrimBoxとArtBoxは仕上り紙面サイズで値は同一。Bleedは裁ち落とし領域を含んだサイズ。デフォルトは上下左右に3mmずつ大きい)を埋め込み。

はまだやっていない。

**Comment by aminophen** [comment]
@kmuto さん： 05439b4 で大雑把に実装してみました。ドライバ依存の機能なので，デフォルトでは enable せず，pdfbox というオプションで使えるようにしました。

現時点での動作：

- \usepackage[pdfbox]{pxgentombow} あるいは \usepackage[pdfbox]{gentombow} とすると，デジタルトンボ作成機能が enable されます。
- TrimBox と BleedBox だけを書き込みます。CropBox と ArtBox は明示しません。
- 利用可能なのは，pdflatex / (u)platex + dvipdfmx / (u)platex + dvips です。lualatex はまだテストしていませんが， \RequirePackage{luatex85} を冒頭に書くと，動く可能性があります。
- 上記のうち後の2つ，すなわち DVI を経由する場合，pxgentombow または gentombow よりも**前**に，以下の 3 つのうちどれかを \usepackage しておいてください。ドライバオプションはそちらか，もしくは \documentclass の所に指定してやってください。（その結果を (px)gentombow が引き継ぎます。）
    - graphicx
    - graphics
    - color
- \mag が 1000 でない場合（jsclasses の 10pt 以外の時など）は全然考えていません。
- なお，オプション名や動作させ方はあまり考えていないので，今後変える可能性があります。

(*1) luatex85 は「LuaTeX 0.85 以降をあたかも pdfTeX みたいに見せるパッケージ」です。（互換性がないので，過渡的な利用をサポートしているやつ）

**Comment by aminophen** [comment]
追加：TrimBox と BleedBox だけを書き込みます。CropBox と ArtBox は明示しません。

**Comment by aminophen** [comment]
謝辞：dvips 用のコードは [ZR さんのコード](https://gist.github.com/zr-tex8r/9c9114d09cdd20953ea32101f71d832a)をベースにしています。

**Comment by aminophen** [comment]
と思ったら，あちらでもほぼ同時に実装してきたようです。 https://github.com/abenori/jlreq/issues/26#issuecomment-380796322

両方リリースされたとしても，両方同時に使われることはあり得ないので，まあ衝突はしないだろうということで。私の方の実装について，考えていることがいくつか：

- BleedBox の 3mm は固定していますが，これを可変にするのであれば「見える方のトンボマーク」も 3mm から変更できるべき，な気がするので，逡巡しています。（カーネル側のトンボ機能が 3mm 固定であるところが難ありで，そこは gentombow がコアを提供しているところに利があるはず。）
- lualatex 対応は難しくないので，後日やります。

**Comment by abenori** [comment]
あっちです．あっちは消した方がいいですかね．

**Comment by kmuto** [comment]
ありがとうございます！ ひとまず@aminophenさんのを試してみました。
先日のテストリポジトリのt2.texにuplatex+[dvipdfmx]graphicx+dvipdfmxをかけてうまく動きました！（Acrobatでも確認）

> 可変にするのであれば「見える方のトンボマーク」も 3mm から変更できるべき，な気がする

そのとおりですね…。InDesignで試したところ、当たり前ではありますがちゃんとトンボマークのアキ幅が変わりました。たいていの本はドブ3mmなんですが、分厚いのだと5mmだったり、海外印刷だと8mmというのがあったりします（どんだけな印刷精度なんだ…）。

**Comment by aminophen** [comment]
> jlreq-tombow

どちらでもー。jlreq でどこまで提供したいか等の方針は私はわからないので。ただ，今そちらにあってこっちにない機能は参考にさせて頂こうか，とも思っています。

**Comment by aminophen** [comment]
以下の機能を追加したバージョン 2018/05/17 v0.9g を CTAN に出しました。

- pxgentombow パッケージは gentombow パッケージに統合しました。pxgentombow は今後 obsolete にしていくつもりなので警告を出していますが，それ以外はどちらも全く同じ動作をします。
- \usepackage[pdfbox]{gentombow} でデジタルトンボ作成機能が enable されます。
    - /TrimBox （仕上がり紙面サイズ）と /BleedBox （塗り足し幅を含めたサイズ）を書き込みます。
    - /ArtBox と /CropBox は書き込みません。
    - /MediaBox については，用紙サイズ設定（papersize special 等）が有効になります。
- \settombowbleed{5mm} とするとドブ（塗り足し）の幅が 5mm になります。\settombowbleed は引数を一つ取り，そこには任意の寸法を入れられます（デフォルトは 3mm）。
- \settombowcolor{\color[cmyk]{0,1,0,0}} とするとトンボの色がマゼンタになります。\settombowcolor は引数を一つ取り，そこには任意の色を入れられます。\usepackage{xcolor} などのパッケージ読み込みはユーザ側で行ってください。

デジタルトンボ作成機能 (pdfbox) はドライバ依存のため，以下の動作条件が課されます。

- pdfLaTeX / LuaLaTeX / XeLaTeX で使う場合は，自動判定されるので特に意識は不要です。
- LaTeX (pLaTeX, upLaTeX) + dvipdfmx / dvips で使う場合は，ドライバオプションが必要です。ただし，gentombow よりも前に graphics/color 系のパッケージが読まれていれば，ドライバオプションを書かなくても自動的に引き継ぐようになっています。

また，pdfbox については「\mag が 1000 でない場合（jsclasses の 10pt 以外の時など）」の動作を考慮していません。jsclasses は nomag あるいは nomag* で使ってください。
